"""
03_audit_qualite.py  (REPARE S08 - 14/06/2026)
Audit COMPLET des transcrits Whisper Belkhayate (les 110, pas un echantillon).

Ce que fait ce script :
  1. Lit TOUS les .txt nouveaux (110) + tous les anciens (142) pour comparaison.
  2. Detecte les marqueurs d'hallucination (NotebookLM, Claude Opus, etc.).
  3. Detecte la langue (FR / EN / mixte) car les transcrits Whisper sont bilingues.
  4. Compte les termes Belkhayate authentiques (liste FR + EN).
  5. Calcule un score /100 par fichier.
  6. Etiquette chaque fichier : source / methode / fiabilite (defiance documentaire).
  7. Produit AUDIT_QUALITE.md (rapport) + MANIFESTE_TRANSCRITS.csv (etiquetage machine).
Aucune ecriture dans les transcrits eux-memes : l'etiquetage vit dans le manifeste.
"""

import os
import csv
from datetime import datetime

# REGLE 1 : chemins absolus C:\trading-copilote
BASE_DIR = r"C:\trading-copilote"

DIR_ANCIEN = os.path.join(BASE_DIR, "03-transcriptions", "transcripts-bruts")
DIR_NOUVEAU = os.path.join(
    BASE_DIR, "03-transcriptions", "nouvelles-sources", "belkhayate-youtube", "transcripts"
)
DOSSIER_SORTIE = os.path.join(
    BASE_DIR, "03-transcriptions", "nouvelles-sources", "belkhayate-youtube"
)
RAPPORT_PATH = os.path.join(DOSSIER_SORTIE, "AUDIT_QUALITE.md")
MANIFESTE_PATH = os.path.join(DOSSIER_SORTIE, "MANIFESTE_TRANSCRITS.csv")

# --- Marqueurs d'hallucination (anciens transcrits NotebookLM) ---
# NB : "v2.1" retire (P2 audit S08) car faux positifs possibles sur du texte legitime.
MARQUEURS_HALLUCINATION = [
    "generateur-prompts-pro", "claude opus", "notebooklm", "generated by",
    "intelligence artificielle a genere", "ce document a ete",
]

# --- Termes Belkhayate authentiques (FR + EN, car Whisper est bilingue) ---
TERMES_BELKHAYATE = [
    "belkhayate", "centre de gravite", "bande", "timing", "oscillateur",
    "energie", "direction", "pivot", "support", "resistance", "bougie",
    "petrole", "cuivre", "ble", "fibonacci", "stochastique", "achat", "vente",
    "signal", "entree", "sortie", "tendance", "impulsion", "couloir",
    "belgrade", "gravity", "gravity center", "range bar", "ticks", "trend",
    "buy", "sell", "profit", "stop loss", "channel", "market",
    "1.618", "1,618", "0.618", "0,618", "180",
]

# --- Detection de langue (heuristique mots vides) ---
MOTS_FR = [" le ", " la ", " les ", " et ", " est ", " vous ", " donc ",
           " marche ", " ici ", " nous ", " pour ", " une ", " des "]
MOTS_EN = [" the ", " and ", " is ", " you ", " here ", " market ", " of ",
           " to ", " we ", " for ", " this ", " that ", " with "]


def lire_tous(dossier):
    """Lit TOUS les .txt d'un dossier (pas d'echantillon)."""
    if not os.path.exists(dossier):
        return []
    resultats = []
    for nom in sorted(os.listdir(dossier)):
        if not nom.endswith(".txt"):
            continue
        chemin = os.path.join(dossier, nom)
        try:
            with open(chemin, "r", encoding="utf-8", errors="ignore") as f:
                contenu = f.read()
            resultats.append({"nom": nom, "contenu": contenu})
        except Exception:
            pass
    return resultats


def detecter_hallucinations(contenu):
    bas = contenu.lower()
    return [m for m in MARQUEURS_HALLUCINATION if m.lower() in bas]


def compter_termes_belkhayate(contenu):
    bas = contenu.lower()
    trouves = [t for t in TERMES_BELKHAYATE if t.lower() in bas]
    return len(trouves), trouves


def detecter_langue(contenu):
    bas = " " + contenu.lower() + " "
    fr = sum(bas.count(m) for m in MOTS_FR)
    en = sum(bas.count(m) for m in MOTS_EN)
    if fr == 0 and en == 0:
        return "?"
    ratio = fr / (fr + en)
    if ratio >= 0.65:
        return "FR"
    if ratio <= 0.35:
        return "EN"
    return "mixte"


def score_qualite(contenu):
    score = 50
    nb_mots = len(contenu.split())
    if nb_mots > 500:
        score += 20
    elif nb_mots > 200:
        score += 10
    elif nb_mots < 50:
        score -= 20
    nb_termes, _ = compter_termes_belkhayate(contenu)
    score += min(nb_termes * 3, 20)
    score -= len(detecter_hallucinations(contenu)) * 15
    return max(0, min(100, score))


def etiqueter(nom, contenu):
    """Etiquetage 1 fichier (defiance documentaire)."""
    nb_mots = len(contenu.split())
    hall = detecter_hallucinations(contenu)
    nb_termes, _ = compter_termes_belkhayate(contenu)
    langue = detecter_langue(contenu)
    score = score_qualite(contenu)

    # source / methode pilotes par le DOSSIER (provenance verifiable), pas par le titre.
    # (P2 audit S08) : tous ces .txt proviennent du scrape de la chaine officielle
    # Belkhayate -> methode=belkhayate. Le titre sert seulement de transparence.
    source = "belkhayate-youtube (chaine officielle)"
    methode = "belkhayate"
    titre_cite_belkhayate = "oui" if "belkhayate" in nom.lower() else "non"

    if hall:
        fiabilite = "INVALIDE"
    elif nb_mots >= 200 and nb_termes >= 1:
        fiabilite = "VALIDE"
    else:
        fiabilite = "A_VERIFIER"

    return {
        "fichier": nom,
        "source": source,
        "methode": methode,
        "titre_cite_belkhayate": titre_cite_belkhayate,
        "langue": langue,
        "mots": nb_mots,
        "termes_belkhayate": nb_termes,
        "hallucinations": len(hall),
        "score": score,
        "fiabilite": fiabilite,
    }


def main():
    print("=" * 64)
    print("AUDIT QUALITE COMPLET - Transcrits Whisper Belkhayate (les 110)")
    print("=" * 64)

    anciens = lire_tous(DIR_ANCIEN)
    nouveaux = lire_tous(DIR_NOUVEAU)
    print("\nAnciens (NotebookLM) : %d fichiers" % len(anciens))
    print("Nouveaux (Whisper)   : %d fichiers" % len(nouveaux))

    manifeste = [etiqueter(f["nom"], f["contenu"]) for f in nouveaux]

    total_hall = sum(r["hallucinations"] for r in manifeste)
    nb_valides = sum(1 for r in manifeste if r["fiabilite"] == "VALIDE")
    nb_verifier = sum(1 for r in manifeste if r["fiabilite"] == "A_VERIFIER")
    nb_invalides = sum(1 for r in manifeste if r["fiabilite"] == "INVALIDE")
    nb_titre_non = sum(1 for r in manifeste if r["titre_cite_belkhayate"] == "non")
    score_moy = round(sum(r["score"] for r in manifeste) / len(manifeste), 1) if manifeste else 0
    mots_moy = round(sum(r["mots"] for r in manifeste) / len(manifeste)) if manifeste else 0
    langues = {}
    for r in manifeste:
        langues[r["langue"]] = langues.get(r["langue"], 0) + 1

    total_hall_ancien = sum(len(detecter_hallucinations(f["contenu"])) for f in anciens)

    print("\nScore moyen /100      : %s" % score_moy)
    print("Mots moyens / fichier : %s" % mots_moy)
    print("Langues               : %s" % langues)
    print("Hallucinations (110)  : %d" % total_hall)
    print("Hallucinations anciens: %d" % total_hall_ancien)
    print("Titre sans 'Belkhayate' (provenance dossier) : %d" % nb_titre_non)
    print("\nVALIDE=%d  A_VERIFIER=%d  INVALIDE=%d" % (nb_valides, nb_verifier, nb_invalides))

    # --- Ecriture MANIFESTE CSV ---
    champs = ["fichier", "source", "methode", "titre_cite_belkhayate", "langue",
              "mots", "termes_belkhayate", "hallucinations", "score", "fiabilite"]
    with open(MANIFESTE_PATH, "w", encoding="utf-8-sig", newline="") as f:
        w = csv.DictWriter(f, fieldnames=champs)
        w.writeheader()
        for r in sorted(manifeste, key=lambda x: x["fichier"]):
            w.writerow(r)

    # --- Ecriture RAPPORT MD ---
    L = []
    L.append("# AUDIT QUALITE TRANSCRITS - COMPLET (les 110)\n\n")
    L.append("**Date** : %s\n\n" % datetime.now().strftime("%d/%m/%Y %H:%M"))
    L.append("## 1. SYNTHESE\n\n")
    L.append("| Indicateur | Anciens (NotebookLM) | Nouveaux (Whisper) |\n")
    L.append("|---|---|---|\n")
    L.append("| Total fichiers | %d | %d |\n" % (len(anciens), len(nouveaux)))
    L.append("| Hallucinations detectees | %d | %d |\n" % (total_hall_ancien, total_hall))
    L.append("| Score moyen /100 | - | %s |\n" % score_moy)
    L.append("| Mots moyens / fichier | - | %s |\n\n" % mots_moy)
    L.append("Langues (nouveaux) : %s\n\n" % ", ".join("%s=%d" % (k, v) for k, v in langues.items()))
    L.append("## 2. VERDICT FIABILITE (110 transcrits)\n\n")
    L.append("- VALIDE : **%d**\n" % nb_valides)
    L.append("- A_VERIFIER : **%d**\n" % nb_verifier)
    L.append("- INVALIDE : **%d**\n\n" % nb_invalides)
    L.append("Provenance : 100%% chaine officielle Belkhayate (dossier). "
             "%d/110 ont un titre qui ne cite pas 'Belkhayate' mais restent source Belkhayate.\n\n" % nb_titre_non)
    if total_hall == 0:
        L.append("> Aucun marqueur d'hallucination sur les 110 transcrits Whisper.\n\n")
    L.append("Etiquetage detaille machine : voir `MANIFESTE_TRANSCRITS.csv`.\n\n")
    L.append("## 3. DETAIL PAR FICHIER (les 110)\n\n")
    L.append("| Fichier | Langue | Mots | Termes | Hall. | Score | Fiabilite |\n")
    L.append("|---|---|---|---|---|---|---|\n")
    for r in sorted(manifeste, key=lambda x: x["fichier"]):
        nom_court = r["fichier"].replace("|", "/")
        L.append("| %s | %s | %d | %d | %d | %d | %s |\n" % (
            nom_court, r["langue"], r["mots"], r["termes_belkhayate"],
            r["hallucinations"], r["score"], r["fiabilite"]))

    with open(RAPPORT_PATH, "w", encoding="utf-8") as f:
        f.writelines(L)

    print("\nRapport   : %s" % RAPPORT_PATH)
    print("Manifeste : %s" % MANIFESTE_PATH)
    print("=" * 64)


if __name__ == "__main__":
    main()
