"""
03_audit_qualite.py
Audit comparatif : anciennes transcriptions (NotebookLM) vs nouvelles (Whisper reel)
Detecte les hallucinations, compare la qualite, produit un rapport .md
"""

import os
import random
import json
from datetime import datetime

BASE_DIR = r"C:\trading-copilote"

DIR_ANCIEN = os.path.join(BASE_DIR, "03-transcriptions", "transcripts-bruts")
DIR_NOUVEAU = os.path.join(BASE_DIR, "03-transcriptions", "nouvelles-sources", "belkhayate-youtube", "transcripts")
RAPPORT_PATH = os.path.join(BASE_DIR, "03-transcriptions", "nouvelles-sources", "belkhayate-youtube", "AUDIT_QUALITE.md")

# Marqueurs d'hallucination connus dans les anciennes transcriptions
MARQUEURS_HALLUCINATION = [
    "generateur-prompts-pro",
    "Claude Opus 4.7",
    "claude opus 4.7",
    "NotebookLM",
    "notebooklm",
    "generated by",
    "Generated by",
    "intelligence artificielle a genere",
    "ce document a ete",
    "version: 2.",
    "v2.1",
    "v1.",
]

# Termes Belkhayate authentiques attendus dans les vraies transcriptions
TERMES_BELKHAYATE = [
    "BGC", "bande", "gravity", "centre de gravite",
    "timing", "oscillateur", "energie", "direction",
    "pivot", "support", "resistance", "bougie",
    "or", "petrole", "cuivre", "ble",
    "fibonacci", "1.618", "stochastique",
    "achat", "vente", "signal", "entree", "sortie",
]


def lire_fichiers(dossier, nb_max=10):
    """Lit nb_max fichiers .txt aleatoires dans un dossier."""
    if not os.path.exists(dossier):
        return []
    fichiers = [f for f in os.listdir(dossier) if f.endswith(".txt")]
    if not fichiers:
        return []
    sample = random.sample(fichiers, min(nb_max, len(fichiers)))
    resultats = []
    for nom in sample:
        chemin = os.path.join(dossier, nom)
        try:
            with open(chemin, "r", encoding="utf-8", errors="ignore") as f:
                contenu = f.read()
            resultats.append({"nom": nom, "contenu": contenu, "chemin": chemin})
        except Exception:
            pass
    return resultats


def detecter_hallucinations(contenu):
    """Retourne la liste des marqueurs d'hallucination trouves."""
    trouves = []
    contenu_lower = contenu.lower()
    for marqueur in MARQUEURS_HALLUCINATION:
        if marqueur.lower() in contenu_lower:
            trouves.append(marqueur)
    return trouves


def compter_termes_belkhayate(contenu):
    """Compte combien de termes Belkhayate authentiques sont presents."""
    contenu_lower = contenu.lower()
    trouves = [t for t in TERMES_BELKHAYATE if t.lower() in contenu_lower]
    return len(trouves), trouves


def score_qualite(contenu, source="nouveau"):
    """
    Calcule un score de qualite /100.
    - Source nouvelle : penalite pour hallucinations, bonus pour termes Belkhayate
    - Source ancienne : meme logique pour comparaison
    """
    score = 50  # base

    # Longueur (une vraie transcription est plus longue)
    nb_mots = len(contenu.split())
    if nb_mots > 500:
        score += 20
    elif nb_mots > 200:
        score += 10
    elif nb_mots < 50:
        score -= 20

    # Termes Belkhayate
    nb_termes, _ = compter_termes_belkhayate(contenu)
    score += min(nb_termes * 3, 20)

    # Hallucinations
    hallucinations = detecter_hallucinations(contenu)
    score -= len(hallucinations) * 15

    return max(0, min(100, score))


def extraire_extrait(contenu, nb_chars=300):
    """Extrait les premiers nb_chars caracteres significatifs."""
    lignes = [l.strip() for l in contenu.split("\n") if l.strip()]
    texte = " ".join(lignes)
    return texte[:nb_chars] + ("..." if len(texte) > nb_chars else "")


def main():
    print("=" * 60)
    print("AUDIT QUALITE : Anciennes vs Nouvelles transcriptions")
    print("=" * 60)

    # Lecture des fichiers
    anciens = lire_fichiers(DIR_ANCIEN, nb_max=10)
    nouveaux = lire_fichiers(DIR_NOUVEAU, nb_max=10)

    nb_anciens_total = len([f for f in os.listdir(DIR_ANCIEN) if f.endswith(".txt")]) if os.path.exists(DIR_ANCIEN) else 0
    nb_nouveaux_total = len([f for f in os.listdir(DIR_NOUVEAU) if f.endswith(".txt")]) if os.path.exists(DIR_NOUVEAU) else 0

    print(f"\nAnciennes transcriptions (total) : {nb_anciens_total} fichiers")
    print(f"Nouvelles transcriptions (total)  : {nb_nouveaux_total} fichiers")
    print(f"\nEchantillon analyse : {len(anciens)} anciens + {len(nouveaux)} nouveaux")

    # Analyse des anciens
    resultats_anciens = []
    total_hall_ancien = 0
    for f in anciens:
        hall = detecter_hallucinations(f["contenu"])
        nb_termes, termes = compter_termes_belkhayate(f["contenu"])
        score = score_qualite(f["contenu"], "ancien")
        total_hall_ancien += len(hall)
        resultats_anciens.append({
            "nom": f["nom"],
            "score": score,
            "mots": len(f["contenu"].split()),
            "hallucinations": hall,
            "termes_belkhayate": nb_termes,
            "extrait": extraire_extrait(f["contenu"])
        })

    # Analyse des nouveaux
    resultats_nouveaux = []
    total_hall_nouveau = 0
    for f in nouveaux:
        hall = detecter_hallucinations(f["contenu"])
        nb_termes, termes = compter_termes_belkhayate(f["contenu"])
        score = score_qualite(f["contenu"], "nouveau")
        total_hall_nouveau += len(hall)
        resultats_nouveaux.append({
            "nom": f["nom"],
            "score": score,
            "mots": len(f["contenu"].split()),
            "hallucinations": hall,
            "termes_belkhayate": nb_termes,
            "extrait": extraire_extrait(f["contenu"])
        })

    # Scores moyens
    score_moy_ancien = round(sum(r["score"] for r in resultats_anciens) / len(resultats_anciens), 1) if resultats_anciens else 0
    score_moy_nouveau = round(sum(r["score"] for r in resultats_nouveaux) / len(resultats_nouveaux), 1) if resultats_nouveaux else 0
    mots_moy_ancien = round(sum(r["mots"] for r in resultats_anciens) / len(resultats_anciens)) if resultats_anciens else 0
    mots_moy_nouveau = round(sum(r["mots"] for r in resultats_nouveaux) / len(resultats_nouveaux)) if resultats_nouveaux else 0

    print(f"\n{'INDICATEUR':<35} {'ANCIENNES':>12} {'NOUVELLES':>12}")
    print("-" * 60)
    print(f"{'Score qualite moyen /100':<35} {score_moy_ancien:>12} {score_moy_nouveau:>12}")
    print(f"{'Mots moyens par fichier':<35} {mots_moy_ancien:>12} {mots_moy_nouveau:>12}")
    print(f"{'Marqueurs hallucination detectes':<35} {total_hall_ancien:>12} {total_hall_nouveau:>12}")

    # Verdict
    print("\n" + "=" * 60)
    if total_hall_ancien > 0:
        print(f"VERDICT ANCIENS : {total_hall_ancien} hallucination(s) detectee(s) -> INVALIDES")
    else:
        print("VERDICT ANCIENS : Aucune hallucination detectee dans l'echantillon")

    if total_hall_nouveau == 0 and score_moy_nouveau >= 60:
        print(f"VERDICT NOUVEAUX : Score {score_moy_nouveau}/100 -> VALIDES")
    elif total_hall_nouveau == 0:
        print(f"VERDICT NOUVEAUX : Score {score_moy_nouveau}/100 -> ACCEPTABLES (verifier manuellement)")
    else:
        print(f"VERDICT NOUVEAUX : {total_hall_nouveau} probleme(s) detecte(s) -> VERIFIER")

    # Generation du rapport Markdown
    lignes = []
    lignes.append(f"# AUDIT QUALITE TRANSCRIPTIONS\n")
    lignes.append(f"**Date** : {datetime.now().strftime('%d/%m/%Y %H:%M')}\n")
    lignes.append(f"**Echantillon** : {len(anciens)} anciens / {len(nouveaux)} nouveaux\n\n")

    lignes.append("## SYNTHESE COMPARATIVE\n")
    lignes.append(f"| Indicateur | Anciennes (NotebookLM) | Nouvelles (Whisper) |\n")
    lignes.append(f"|------------|------------------------|---------------------|\n")
    lignes.append(f"| Total fichiers | {nb_anciens_total} | {nb_nouveaux_total} |\n")
    lignes.append(f"| Score qualite moyen /100 | {score_moy_ancien} | {score_moy_nouveau} |\n")
    lignes.append(f"| Mots moyens par fichier | {mots_moy_ancien} | {mots_moy_nouveau} |\n")
    lignes.append(f"| Marqueurs hallucination | {total_hall_ancien} | {total_hall_nouveau} |\n\n")

    lignes.append("## VERDICT\n")
    if total_hall_ancien > 0:
        lignes.append(f"- **ANCIENS** : {total_hall_ancien} hallucination(s) confirmee(s) → a SUPPRIMER apres validation des nouveaux\n")
    if total_hall_nouveau == 0 and score_moy_nouveau >= 60:
        lignes.append(f"- **NOUVEAUX** : Score {score_moy_nouveau}/100 → VALIDES, prets pour extraction KB\n\n")
    else:
        lignes.append(f"- **NOUVEAUX** : Score {score_moy_nouveau}/100 → verification manuelle recommandee\n\n")

    lignes.append("## DETAIL ANCIENNES TRANSCRIPTIONS (echantillon)\n\n")
    for r in resultats_anciens:
        lignes.append(f"### {r['nom']}\n")
        lignes.append(f"- Score : {r['score']}/100 | Mots : {r['mots']} | Termes Belkhayate : {r['termes_belkhayate']}\n")
        if r['hallucinations']:
            lignes.append(f"- ⚠️ Hallucinations : {', '.join(r['hallucinations'])}\n")
        lignes.append(f"- Extrait : *{r['extrait']}*\n\n")

    lignes.append("## DETAIL NOUVELLES TRANSCRIPTIONS (echantillon)\n\n")
    for r in resultats_nouveaux:
        lignes.append(f"### {r['nom']}\n")
        lignes.append(f"- Score : {r['score']}/100 | Mots : {r['mots']} | Termes Belkhayate : {r['termes_belkhayate']}\n")
        if r['hallucinations']:
            lignes.append(f"- ⚠️ Hallucinations : {', '.join(r['hallucinations'])}\n")
        lignes.append(f"- Extrait : *{r['extrait']}*\n\n")

    with open(RAPPORT_PATH, "w", encoding="utf-8") as f:
        f.writelines(lignes)

    print(f"\nRapport genere : {RAPPORT_PATH}")
    print("=" * 60)


if __name__ == "__main__":
    main()
