"""
03_audit_qualite.py  (REPARE S08 - 14/06/2026)
Audit COMPLET des transcrits Whisper Belkhayate (les 110, pas un echantillon).

Ce que fait ce script :
  1. Lit TOUS les .txt du dossier nouveaux transcrits (110) + tous les anciens (142) pour comparaison.
  2. Detecte les marqueurs d'hallucination (NotebookLM, Claude Opus, etc.).
  3. Detecte la langue (FR / EN / mixte) car les transcrits Whisper sont bilingues.
  4. Compte les termes Belkhayate authentiques (liste FR + EN).
  5. Calcule un score /100 par fichier.
  6. Etiquette chaque fichier : source / methode / fiabilite (defiance documentaire).
  7. Produit DEUX sorties :
       - AUDIT_QUALITE.md          (rapport lisible, les 110)
       - MANIFESTE_TRANSCRITS.csv  (etiquetage machine : 1 ligne par fichier)

Aucune ecriture dans les transcrits eux-memes : l'etiquetage vit dans le manifeste.
"""

import os
import csv
from datetime import datetime

# REGLE 1 : chemins absolus C:\trading-copilote
BASE_DIR = r"C:\trading-copilote"

DIR_ANCIEN = os.path.join(BASE_DIR, "03-transcriptions", "transcripts-bruts")
DIR_NOUVEAU = os.path.join(
    BASE_DIR, "03-transcriptions", "nouvelles-sources", "belkhayate-youtube", "transcripts"
)
DOSSIER_SORTIE = os.path.join(
    BASE_DIR, "03-transcriptions", "nouvelles-sources", "belkhayate-youtube"
)
RAPPORT_PATH = os.path.join(DOSSIER_SORTIE, "AUDIT_QUALITE.md")
MANIFESTE_PATH = os.path.join(DOSSIER_SORTIE, "MANIFESTE_TRANSCRITS.csv")

# --- Marqueurs d'hallucination (anciens transcrits NotebookLM) ---
MARQUEURS_HALLUCINATION = [
    "generateur-prompts-pro", "claude opus", "notebooklm", "generated by",
    "intelligence artificielle a genere", "ce document a ete", "v2.1",
]

# --- Termes Belkhayate authentiques (FR + EN, car Whisper est bilingue) ---
TERMES_BELKHAYATE = [
    # FR
    "belkhayate", "centre de gravite", "bande", "timing", "oscillateur",
    "energie", "direction", "pivot", "support", "resistance", "bougie",
    "petrole", "cuivre", "ble", "fibonacci", "stochastique", "achat", "vente",
    "signal", "entree", "sortie", "tendance", "impulsion", "couloir",
    # EN (et la mauvaise transcription "belgrade" = belkhayate)
    "belgrade", "gravity", "gravity center", "range bar", "ticks", "trend",
    "buy", "sell", "profit", "stop loss", "channel", "market",
    # chiffres methode
    "1.618", "1,618", "0.618", "0,618", "180",
]

# --- Detection de langue (heuristique mots vides) ---
MOTS_FR = [" le ", " la ", " les ", " et ", " est ", " vous ", " donc ",
           " marche ", " ici ", " nous ", " pour ", " une ", " des "]
MOTS_EN = [" the ", " and ", " is ", " you ", " here ", " market ", " of ",
           " to ", " we ", " for ", " this ", " that ", " with "]


def lire_tous(dossier):
    """Lit TOUS les .txt d'un dossier (pas d'echantillon)."""
    if not os.path.exists(dossier):
        return []
    resultats = []
    for nom in sorted(os.listdir(dossier)):
        if not nom.endswith(".txt"):
            continue
        chemin = os.path.join(dossier, nom)
        try:
            with open(chemin, "r", encoding="utf-8", errors="ignore") as f:
                contenu = f.read()
            resultats.append({"nom": nom, "contenu": contenu, "chemin": chemin})
        except Exception:
            pass
    return resultats


def detecter_hallucinations(contenu):
    bas = contenu.lower()
    return [m for m in MARQUEURS_HALLUCINATION if m.lower() in bas]


def compter_termes_belkhayate(contenu):
    bas = contenu.lower()
    trouves = [t for t in TERMES_BELKHAYATE if t.lower() in bas]
    return len(trouves), trouves


def detecter_langue(contenu):
    bas = " " + contenu.lower() + " "
    fr = sum(bas.count(m) for m in MOTS_FR)
    en = sum(bas.count(m) for m in MOTS_EN)
    if fr == 0 and en == 0:
        return "?"
    ratio = fr / (fr + en)
    if ratio >= 0.65:
        return "FR"
    if ratio <= 0.35:
        return "EN"
    return "mixte"


def score_qualite(contenu):
    score = 50
    nb_mots = len(contenu.split())
    if nb_mots > 500:
        score += 20
    elif nb_mots > 200:
        score += 10
    elif nb_mots < 50:
        score -= 20
    nb_termes, _ = compter_termes_belkhayate(contenu)
    score += min(nb_termes * 3, 20)
    score -= len(detecter_hallucinations(contenu)) * 15
    return max(0, min(100, score))


def etiqueter(nom, contenu):
    """Etiquetage 1 fichier (defiance documentaire)."""
    nb_mots = len(contenu.split())
    hall = detecter_hallucinations(contenu)
    nb_termes, _ = compter_termes_belkhayate(contenu)
    langue = detecter_langue(contenu)
    score = score_qualite(contenu)

    # source / methode pilotes par le nom de fichier (couche canonique)
    nom_bas = nom.lower()
    if "belkhayate" in nom_bas:
        source = "belkhayate-youtube (chaine officielle)"
        methode = "belkhayate"
    else:
        source = "belkhayate-youtube"
        methode = "belkhayate?"  # nom ne dit pas Belkhayate -> a confirmer

    # fiabilite
    if hall:
        fiabilite = "INVALIDE"        # hallucination presente
    elif nb_mots >= 200 and nb_termes >= 1 and methode == "belkhayate":
        fiabilite = "VALIDE"
    else:
        fiabilite = "A_VERIFIER"

    return {
        "fichier": nom,
        "source": source,
        "methode": methode,
        "langue": langue,
        "mots": nb_mots,
        "termes_belkhayate": nb_termes,
        "hallucinations": len(hall),
        "score": score,
        "fiabilite": fiabilite,
    }


def main():
    print("=" * 64)
    print("AUDIT QUALITE COMPLET - Transcrits Whisper Belkhayate (les 110)")
    print("=" * 64)

    anciens = lire_tous(DIR_ANCIEN)
    nouveaux = lire_tous(DIR_NOUVEAU)
    print(f"\nAnciens (NotebookLM) : {len(anciens)} fichiers")
    print(f"Nouveaux (Whisper)   : {len(nouveaux)} fichiers")

    # --- Etiquetage des 110 nouveaux ---
    manifeste = [etiqueter(f["nom"], f["contenu"]) for f in nouveaux]

    total_hall = sum(r["hallucinations"] for r in manifeste)
    nb_valides = sum(1 for r in manifeste if r["fiabilite"] == "VALIDE")
    nb_verifier = sum(1 for r in manifeste if r["fiabilite"] == "A_VERIFIER")
    nb_invalides = sum(1 for r in manifeste if r["fiabilite"] == "INVALIDE")
    score_moy = round(sum(r["score"] for r in manifeste) / len(manifeste), 1) if manifeste else 0
    mots_moy = round(sum(r["mots"] for r in manifeste) / len(manifeste)) if manifeste else 0
    langues = {}
    for r in manifeste:
        langues[r["langue"]] = langues.get(r["langue"], 0) + 1

    # comparaison anciens (hallucinations seulement, echantillon = tous)
    total_hall_ancien = sum(len(detecter_hallucinations(f["contenu"])) for f in anciens)

    print(f"\nScore moyen /100      : {score_moy}")
    print(f"Mots moyens / fichier : {mots_moy}")
    print(f"Langues               : {langues}")
    print(f"Hallucinations (110)  : {total_hall}")
    print(f"Hallucinations anciens: {total_hall_ancien}")
    print(f"\nVALIDE={nb_valides}  A_VERIFIER={nb_verifier}  INVALIDE={nb_invalides}")

    # --- Ecriture MANIFESTE CSV ---
    with open(MANIFESTE_PATH, "w", encoding="utf-8-sig", newline="") as f:
        champs = ["fichier", "source", "methode", "langue", "mots",
                  "termes_belkhayate", "hallucinations", "score", "fiabilite"]
        w = csv.DictWriter(f, fieldnames=champs)
        w.writeheader()
        for r in sorted(manifeste, key=lambda x: x["fichier"]):
            w.writerow(r)

    # --- Ecriture RAPPORT MD ---
    L = []
    L.append("# AUDIT QUALITE TRANSCRITS - COMPLET (les 110)\n\n")
    L.append(f"**Date** : {datetime.now().strftime('%d/%m/%Y %H:%M')}\n\n")
    L.append("## 1. SYNTHESE\n\n")
    L.append("| Indicateur | Anciens (NotebookLM) | Nouveaux (Whisper) |\n")
    L.append("|---|---|---|\n")
    L.append(f"| Total fichiers | {len(anciens)} | {len(nouveaux)} |\n")
    L.append(f"| Hallucinations detectees | {total_hall_ancien} | {total_hall} |\n")
    L.append(f"| Score moyen /100 | - | {score_moy} |\n")
    L.append(f"| Mots moyens / fichier | - | {mots_moy} |\n\n")
    L.append(f"Langues (nouveaux) : {', '.join(f'{k}={v}' for k, v in langues.items())}\n\n")
    L.append("## 2. VERDICT FIABILITE (110 transcrits)\n\n")
    L.append(f"- VALIDE : **{nb_valides}**\n")
    L.append(f"- A_VERIFIER : **{nb_verifier}**\n")
    L.append(f"- INVALIDE : **{nb_invalides}**\n\n")
    if total_hall == 0:
        L.append("> Aucun marqueur d'hallucination sur les 110 transcrits Whisper.\n\n")
    L.append("Etiquetage detaille machine : voir `MANIFESTE_TRANSCRITS.csv`.\n\n")
    L.append("## 3. DETAIL PAR FICHIER (les 110)\n\n")
    L.append("| Fichier | Langue | Mots | Termes | Hall. | Score | Fiabilite |\n")
    L.append("|---|---|---|---|---|---|---|\n")
    for r in sorted(manifeste, key=lambda x: x["fichier"]):
        nom_court = r["fichier"].replace("|", "/")
        L.append(
            f"| {nom_court} | {r['langue']} | {r['mots']} | "
            f"{r['termes_belkhayate']} | {r['hallucinations']} | "
            f"{r['score']} | {r['fiabilite']} |\n"
        )

    with open(RAPPORT_PATH, "w", encoding="utf-8") as f:
        f.writelines(L)

    print(f"\nRapport   : {RAPPORT_PATH}")
    print(f"Manifeste : {MANIFESTE_PATH}")
    print("=" * 64)


if __name__ == "__main__":
    main()
